/**
 * Autogenerated by Thrift Compiler (0.13.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "calculator_constants.h"

namespace tutorial {

const calculatorConstants g_calculator_constants;

calculatorConstants::calculatorConstants() {
}

} // namespace

